export const LOGIN = 'LOGIN';
export const TOKEN_REQUEST_ERROR = 'TOKEN_REQUEST_ERROR';
export const TOKEN_REQUEST_SUCCESS = 'TOKEN_REQUEST_SUCCESS';
export const QUESTIONS_REQUEST = 'QUESTIONS_REQUEST';
export const SECTION_USER = 'SECTION_USER';
